#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartUserControl, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  solenoid1,      sensorDigitalOut)
#pragma config(Sensor, dgtl2,  solenoid2,      sensorDigitalOut)
#pragma config(Sensor, dgtl5,  frontSonar,     sensorSONAR_mm)
#pragma config(Sensor, dgtl7,  rearSonar,      sensorSONAR_mm)
#pragma config(Sensor, dgtl9,  override,       sensorTouch)
#pragma config(Sensor, I2C_1,  liftLeft,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  intakeLeft,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  driveLeft,      sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  driveRight,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rightArm1,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           intakeRight,   tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           intakeLeft,    tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port4,           driveLeftFront, tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port5,           driveLeftBack, tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port6,           driveRightFront, tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port7,           driveRightBack, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port8,           LiftRight,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           LiftLeft,      tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port10,          leftArm1,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "settings.h"
#include "customCompetition.c"
#include "globalFunctions.c"
#include "pistonControl.c"
#include "PID Turn.c"
#include "autonFunctions.c"
#include "autonSelection.c"
#include "teliopFunctions.c"
#include "autons.c"
#include "watchDog.c"



#pragma platform(VEX)


//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)


void pre_auton()
{
	bStopTasksBetweenModes = true;
if(bIfiRobotDisabled)
{
	resetAllEncoders();
	retractPistons();
}
	if(overrideAll())
	{
  	selectAuton();
		resetGyro();
	}
	//resetGyro(); // MUST BE COMMENTED OUT
}


task autonomous()
{
	if(selectedAuton == 0)      // Red1 auton
		redBigballs();
	else if(selectedAuton == 1) // Red2 auton
		redRear();
	else if(selectedAuton == 3) // Blue1 auton
		blueRear();
	else if(selectedAuton == 4) // Blue2 auton
		blueBigBalls();
	else                        // None or an error happend
  	{
  		displayLCDCenteredString(0, "Just chillin");
  			displayLCDCenteredString(0, "here human");
  		}
}


task usercontrol()
{
	StartTask(watchDog);
	StartTask(driveMain);
	StartTask(armControlMain);
	StartTask(pistonControl);
	StartTask (liftReset);
	while (true)
	  intakeMain();
}
