#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartUserControl, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  solenoid1,      sensorDigitalOut)
#pragma config(Sensor, dgtl2,  solenoid2,      sensorDigitalOut)
#pragma config(Sensor, dgtl5,  frontSonar,     sensorSONAR_mm)
#pragma config(Sensor, dgtl7,  rearSonar,      sensorSONAR_mm)
#pragma config(Sensor, dgtl9,  override,       sensorTouch)
#pragma config(Sensor, I2C_1,  liftLeft,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  intakeLeft,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  driveLeft,      sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  driveRight,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rightArm1,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           intakeRight,   tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           intakeLeft,    tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port4,           driveLeftFront, tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port5,           driveLeftBack, tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port6,           driveRightFront, tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port7,           driveRightBack, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port8,           LiftRight,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           LiftLeft,      tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port10,          leftArm1,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "settings.h"
#include "globalFunctions.c"
#include "pistonControl.c"
#include "PID Turn.c"
#include "autonFunctions.c"
#include "autonSelection.c"
#include "teliopFunctions.c"
#include "autons.c"
#include "watchDog.c"


task main()
{
while(true)
{
if(true)
{
		if((vexRT[Btn7DXmtr2] == 1) && (vexRT[Btn7UXmtr2] == 1))
		{
			while(vexRT[Btn7DXmtr2] || (vexRT[Btn7UXmtr2])
			{
				individualLiftControlXmit2();
			}
			resetLiftEncoderToValue(0);
		}
		else if((vexRT[Btn8DXmtr2] == 1) && (vexRT[Btn8UXmtr2] == 1))
		{
			while(vexRT[Btn8DXmtr2] || (vexRT[Btn8UXmtr2])
			{
				individualLiftControlXmit2();
			}
			resetLiftEncoderToValue(liftDriveTicks);
		}
	}
	else
	{
		wait10Msec(100);
	}
	wait10Msec(10);

}

}
