#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task watchDog()
{
	while(true)
	{
		if(overrideAll())
		{
			StopTask(driveMain);
			StopTask(armControlMain);
			StopTask(pistonControl);
			StopTask(liftReset);
			stopAllMotors();
			while(overrideAll())
			{
				StartTask(driveMain);
				StartTask(armControlMain);
				StartTask(pistonControl);
				StartTask(liftReset);
			}
		}
}
}
